language: java
jdk: openjdk11
services:
  - docker
os: linux
env:
  - IMAGE_NAME="online-radio-search-static-web" IMAGE_VERSION=$(date +"%Y-%m-%d-%H-%M-%S")
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew build -i
  - ls build/
  - ls build/libs/
  - docker build -t "${IMAGE_NAME}" .
after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo "$IMAGE_VERSION"
  - docker tag "${IMAGE_NAME}:${IMAGE_VERSION}"
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
  on:
    branch: master
