language: java
jdk: openjdk11
services:
  - docker
os: linux
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew build -i
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: export VERSION=$(date +"%Y-%m-%d-%H-%M-%S") \
          && docker build -t online-radio-search-static-web . \
          && docker tag online-radio-search-static-web:${VERSION} \
          && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD \
          && docker push online-radio-search-static-web-${VERSION}
  on:
    branch: master
