server.port: 8080

spring:
  application:
    name: ors-web

spring.jackson.deserialization.adjust_dates_to_context_time_zone: false
spring.jackson.serialization.write_dates_as_timestamps: false
spring.jackson.date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

application:
  apiUrl: 'https://api.onlineradiosearch.com'
  latestSearchesClient.size: 50
  radioStationSongsClient.size: 10
  radioStreamsClient.size: 10
  radioStationsClient.size: 10
  searchRadioStationClient.size: 10
  searchSongClient.size: 10
  searchGenreClient.size: 10
  sitemap:
    domain: 'https://onlineradiosearch.com'
    itemsPerPage: 1000
    cacheTime: 24h
  googleAds:
    enabled: false
    clientId: 'myGoogleId'
    mainPageEnabled: true
    radioStationTopEnabled: true
    radioStationDownEnabled: true
    searchPageTopEnabled: true
  propellerAds:
    enabled: false
    domainVerificationCode: 'myDomainVerificationCode'
  googleAnalytics:
    enabled: false
    userId: ''
  addThis:
    enabled: false
    scriptLocation: ''
  disqus:
    enabled: false
    urlPrefix: 'http://localhost'
    accountName: ''