name: Deployment pipeline

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_REGISTRY_NAMESPACE: mkazinauskas
  DOCKER_REGISTRY_ARTIFACT: online-radio-search-web
  KUBERNETES_VERSION: 'latest' # default is latest stable
  KUBERNETES_APP_NAME: online-radio-search-web

jobs:
  build_and_publish:
    name: Building and publishing artifact
    runs-on: ubuntu-20.04
    outputs:
      image_version: ${{ steps.timestamp_generator.outputs.time }}
    steps:
      - name: Project checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build PR
        run: ./gradlew build -i

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Generate image timestamp
        id: timestamp_generator
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Generate image name
        id: image_info
        run: echo "::set-output name=image::${{ env.DOCKER_REGISTRY_NAMESPACE }}/${{ env.DOCKER_REGISTRY_ARTIFACT }}:${{ steps.timestamp_generator.outputs.time }}"

      - name: Build and publish docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.image_info.outputs.image }}
            ${{ env.DOCKER_REGISTRY_NAMESPACE }}/${{ env.DOCKER_REGISTRY_ARTIFACT }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "release/${{ steps.timestamp_generator.outputs.time }}"
          release_name: "Release of `${{ steps.timestamp_generator.outputs.time }}`"
          body: |
            New release of great project!
          draft: false
          prerelease: false

  deploy_to_test:
    name: Deploy application to Test environment
    runs-on: ubuntu-20.04
    needs: build_and_publish
    outputs:
      image_version: ${{ needs.build_and_publish.outputs.image_version }}
    environment:
      name: test
      url: https://github.com/mkazinauskas/github-actions-deployment-pipeline/test
    steps:
      - name: Generate image name
        id: image_info
        run: echo "::set-output name=image::${{ env.DOCKER_REGISTRY_NAMESPACE }}/${{ env.DOCKER_REGISTRY_ARTIFACT }}:${{ needs.build_and_publish.outputs.image_version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Check if image exists in registry
        run: docker pull "${{ steps.image_info.outputs.image }}"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ env.KUBERNETES_VERSION }}

      - name: Make .kube directory
        run: mkdir ~/.kube

      - name: Add kubernetes credentials
        run: echo "${{ secrets.KUBERNETES_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Prepare deployment file
        run: |
          sed -i 's;{{APP_NAME}};${{ env.KUBERNETES_APP_NAME }};g' ".github/workflows/deployments/deployment_template.yaml"
          sed -i 's;{{NAMESPACE}};${{ secrets.NAMESPACE }};g' ".github/workflows/deployments/deployment_template.yaml"
          sed -i 's;{{IMAGE}};${{ steps.image_info.outputs.image }};g' ".github/workflows/deployments/deployment_template.yaml"
          cat ".github/workflows/deployments/deployment_template.yaml"

      - name: Deploy new version
        run: kubectl apply -f ".github/workflows/deployments/deployment_template.yaml"

      - name: Check if deployment successful
        timeout-minutes: 2
        run: kubectl -n ${{ secrets.NAMESPACE }} rollout status deployment ${{ env.KUBERNETES_APP_NAME }}-deployment

  deploy_to_stage:
    name: Deploy application to Stage environment
    runs-on: ubuntu-20.04
    needs: deploy_to_test
    outputs:
      image_version: ${{ needs.deploy_to_test.outputs.image_version }}
    environment:
      name: stage
      url: https://github.com/mkazinauskas/github-actions-deployment-pipeline/stage
    steps:
      - name: Generate image name
        id: image_info
        run: echo "::set-output name=image::${{ env.DOCKER_REGISTRY_NAMESPACE }}/${{ env.DOCKER_REGISTRY_ARTIFACT }}:${{ needs.deploy_to_test.outputs.image_version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Check if image exists in registry
        run: docker pull "${{ steps.image_info.outputs.image }}"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ env.KUBERNETES_VERSION }}

      - name: Make .kube directory
        run: mkdir ~/.kube

      - name: Add kubernetes credentials
        run: echo "${{ secrets.KUBERNETES_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Prepare deployment file
        run: |
          sed -i 's;{{APP_NAME}};${{ env.KUBERNETES_APP_NAME }};g' ".github/workflows/deployments/deployment_template.yaml"
          sed -i 's;{{NAMESPACE}};${{ secrets.NAMESPACE }};g' ".github/workflows/deployments/deployment_template.yaml"
          sed -i 's;{{IMAGE}};${{ steps.image_info.outputs.image }};g' ".github/workflows/deployments/deployment_template.yaml"
          cat ".github/workflows/deployments/deployment_template.yaml"

      - name: Deploy new version
        run: kubectl apply -f ".github/workflows/deployments/deployment_template.yaml"

      - name: Check if deployment successful
        timeout-minutes: 2
        run: kubectl -n ${{ secrets.NAMESPACE }} rollout status deployment ${{ env.KUBERNETES_APP_NAME }}-deployment


  deploy_to_production:
    name: Deploy application to Production environment
    runs-on: ubuntu-20.04
    needs: deploy_to_stage
    environment:
      name: prod
      url: https://github.com/mkazinauskas/github-actions-deployment-pipeline/prod
    steps:
      - name: Generate image name
        id: image_info
        run: echo "::set-output name=image::${{ env.DOCKER_REGISTRY_NAMESPACE }}/${{ env.DOCKER_REGISTRY_ARTIFACT }}:${{ needs.deploy_to_stage.outputs.image_version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Check if image exists in registry
        run: docker pull "${{ steps.image_info.outputs.image }}"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ env.KUBERNETES_VERSION }}

      - name: Make .kube directory
        run: mkdir ~/.kube

      - name: Add kubernetes credentials
        run: echo "${{ secrets.KUBERNETES_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Prepare deployment file
        run: |
          sed -i 's;{{APP_NAME}};${{ env.KUBERNETES_APP_NAME }};g' ".github/workflows/deployments/deployment_template.yaml"
          sed -i 's;{{NAMESPACE}};${{ secrets.NAMESPACE }};g' ".github/workflows/deployments/deployment_template.yaml"
          sed -i 's;{{IMAGE}};${{ steps.image_info.outputs.image }};g' ".github/workflows/deployments/deployment_template.yaml"
          cat ".github/workflows/deployments/deployment_template.yaml"

      - name: Deploy new version
        run: kubectl apply -f ".github/workflows/deployments/deployment_template.yaml"

      - name: Check if deployment successful
        timeout-minutes: 2
        run: kubectl -n ${{ secrets.NAMESPACE }} rollout status deployment ${{ env.KUBERNETES_APP_NAME }}-deployment
